// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/checkboxes/current": {
            "get": {
                "description": "Get the current bitset",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the current bitset",
                "operationId": "get-current-bitset",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetCurrentResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/checkboxes/update": {
            "post": {
                "description": "Update the bitset at a given position",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update the bitset at a given position",
                "operationId": "update-bitset",
                "parameters": [
                    {
                        "description": "Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.GetCurrentResponse": {
            "type": "object",
            "properties": {
                "bitSet": {
                    "type": "string"
                }
            }
        },
        "models.UpdateRequest": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "integer"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "models.UpdateResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
